apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: yeni-klasor-app
  namespace: autoscaleops
  labels:
    release: prometheus          # Prometheus bu label'ı arar
spec:
  selector:
    matchLabels:
      app: yeni-klasor           # yeni-klasor-service'in label'ı
  endpoints:
    - port: http                 # Service'deki port adı
      path: /metrics
      interval: 15s             # 15 saniyede bir scrape
